### ISSUE TITLE
Storing of clients personal data

### ISSUE THREAD

**Issue by camwlsn** [SpeiserK/Group-C---Camp-OAC#2]
One of our requirements is to keep a database of customers so that we can provide customers with information regarding when firewood is available to purchase.

**Comment by SpeiserK** [comment]
Need to figure out a possible web server we can use to run our database, should look into this when configuring tech stack.

**Comment by zachpren0** [comment]
We are using MONGO DB for this. i think we should consider closing this Issue when we upload requirements report.
