### ISSUE TITLE
Research best practices for running backend and frontend server

### ISSUE THREAD

**Issue by zachpren0** [SpeiserK/Group-C---Camp-OAC#71]
Currently we can run two commands, 
NPM start :  runs frontend
Nodemon Server: runs backend node server with connections to mongo DB

Need to figure out a way to run both with one command?

**Comment by SpeiserK** [comment]
Nodemon is ran when 'npm start' is called.
Visit https://www.npmjs.com/package//nodemon for more  info

**Comment by zachpren0** [comment]
How does it grab authentication information for mongoDB?

**Comment by SpeiserK** [comment]
We use mongoose, a library we installed into our backend to access MongoDB. Mongoose comes with a set of functions such as mongoose.connect(uri) which uses a MongoDB generated link string to connect to the database.

We will need to do further research when we start backend dev on how the front end accesses the back end, and if both backend and frontend servers need to be started for full stack communication.

**Comment by SpeiserK** [comment]
You need to run nodemon server and npm start for both front and back end to run. You can call node apis from react to manipulate database.
